### ISSUE TITLE
using CSS pseudo-classes / pseudo-elements breaks the whole style

### ISSUE THREAD

**Issue by clemos** [silexlabs/Cocktail#382]
Using unsupported pseudo selectors such as `:after`, `:before` not only doesn't work,
but it simply removes all other styles, leaving the page completely unstyled.

``` html
<div class='red'>
RED
</div>
<div class='pseudo'>
pseudo
</div>
```

``` css
.red {
  color:#f00;
}
.pseudo:after {
  color:#00f;
}
```

The weird thing is it doesn't seem to be an issue with the CSS parser, because the problem doesn't occur if the `.pseudo` class is not used in the HTML document...
