### ISSUE TITLE
background image of elems with opacity < 1 overflow

### ISSUE THREAD

**Issue by clemos** [silexlabs/Cocktail#390]
``` html
<a href='#' class='picto'></a>
```

``` css
.picto{
  opacity:0.5;
  display:block;
  height:50px;
  width:50px;
  background:url('http://demos.silexlabs.org/trycocktail/img/cocktail.png');
}
.picto:hover {
  opacity:1;
}
```

This will cause the whole picture to be visible, even though the element has a smaller size than its background picture.
On hover, the picture will show correctly (opacity 1).
The issue also appears with other elements (`div`, `span`, etc)

Any thoughts ?

BTW it's kind of unrelated, but 
do you have any pointers as to how to implement CSS3 features such as gradient backgrounds, `text-shadow`, `border-radius`, `box-shadow`, and such...
(I've put them in decreasing order of interest ;))
I'm pretty familiar with the AS3 drawing API, so I believe it's quite possible.
But I don't really know where to start, and have no real idea how tricky this can be.
And did you actually try to do it ?
